In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

# KNN(Scratch)

In [4]:
from collections import Counter
from sklearn import datasets
from sklearn.model_selection import train_test_split

class KNN:
    def __init__(self,k=3):
        self.k = k
        
    def fit(self,X,y):
        self.X_train = X
        self.y_train = y
     
     
        
    def predict(self,X):
        predictions = [self._predict(x) for x in X]
        return np.array(predictions)
    
    
    
    def _predict(self,x):
        
        distances = np.linalg.norm(self.X_train - x,axis=1)
        
        k_indices = np.argsort(distances)[:self.k]
        
        k_nearest_models = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_models).most_common(1)
        
        return most_common[0][0]    
    

    
    
    
    





iris = datasets.load_iris()
X, y = iris.data, iris.target

# Step 2: Split the dataset into training and test sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(y_train)
# Step 3: Create and train the KNN classifier with k=3
knn = KNN(k=3)
knn.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = knn.predict(X_test)
print(y_pred)
# Step 5: Evaluate the accuracy
accuracy = np.sum(y_pred == y_test) / len(y_test)
print("Accuracy of KNN classifier on Iris dataset:", accuracy)

[0 0 1 0 0 2 1 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1
 2 0 1 2 0 2 2 1 1 2 1 0 1 2 0 0 1 1 0 2 0 0 1 1 2 1 2 2 1 0 0 2 2 0 0 0 1
 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1
 1 2 2 0 1 2 0 1 2]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy of KNN classifier on Iris dataset: 1.0


from 

In [5]:
class Knn:
    def __init__(self,k=3):
        self.k = k
        
    def fit(self,X,y):
        self.X_train = X
        self.y_train = y
        
    def predict(self,X):
        predictions = [self._predict(x) for x in X]
        
        return np.array(predictions)
        
        
        
    def _predict(self,x):
        distances = np.linalg.norm(self.X_train - x,axis=1)
        k_indices = np.argsort(distances)[:self.k]
        
        k_nearest_models = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_models).most_common(1)
    
        return most_common[0][0]       


def train_t_split(X,y,test_size=0.3,random_state=None):
    if random_state:
        np.random.seed(random_state)
    n = len(X)
    n_test = int(np.ceil(n*test_size))
    indices = np.random.permutation(n)
    test_indices = indices[:n_test]
    train_indices = indices[n_test:]  
    
    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]
    
    return X_train, X_test, y_train, y_test

    
    
    
data = datasets.load_iris()
X = data.data
y= data.target

X_train, X_test, y_train, y_test = train_t_split(X,y,test_size=0.2)

knn = Knn()
knn.fit(X_train,y_train)

knn.predict(X_test)


        
        

array([1, 2, 2, 0, 1, 2, 2, 2, 1, 2, 0, 2, 0, 2, 1, 2, 1, 0, 0, 1, 2, 1,
       0, 1, 1, 1, 0, 1, 2, 2])

In [10]:
class KnearestN:
    def __init__(self,k=3):
        self.k = k
        
    def fit(self,X,y):
        self.X_train = X
        self.y_train = y
        
    def predict(self,X):
        predictions = [self.__predict(x) for x in X]
        return predictions
    
    def __predict(self,x):
        distances = np.linalg.norm(self.X_train - x,axis=1)
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_models = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_models).most_common(1)
        return most_common
        

knnn = KnearestN()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

np.mean(y_test == y_pred) 
y_test == y_pred
    

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])